### ISSUE TITLE
Error with version 0.2.0, TypeError: argument 1 must be str, not PosixPath

### ISSUE THREAD

**Issue by globophobe** [polm/posuto#5]
```
      8 DBPATH = Path(__file__).parent / 'postaldata.db'
----> 9 CONN = sqlite3.connect(DBPATH)
     10 DB = CONN.cursor()
     11 

TypeError: argument 1 must be str, not PosixPath
```

By downgrading to 0.1.15, I could resolve the problem.

**Comment by polm** [comment]
Thanks for the report and sorry for the trouble.

That's kind of a surprising error. Based on [this issue](https://bugs.python.org/issue33496), maybe you're using Python 3.6? If that's not it, please tell me your Python version and OS. 

If the issue is Python 3.6, then this can be resolved by casting the path to a string, so that won't be a big deal.

**Comment by globophobe** [comment]
Thanks, it was Python 3.6

**Comment by polm** [comment]
OK, I think it should be fixed, could you install the latest alpha with the following and confirm?

    pip install posuto==0.2.1a1

**Comment by globophobe** [comment]
That fixed it. Thanks!

**Comment by polm** [comment]
Thanks for confirming, I'll make an official release.
